plugins {
    id "com.android.application"
}

android {
    namespace "com.cityrestaurant.mobileui"
    compileSdk 35

    defaultConfig {
        applicationId "com.cityrestaurant.mobileui"
        minSdk 24
        targetSdk 35
        versionCode 1
        versionName "0.11.0"
    }
}

dependencies {
}
