plugins {
    id 'com.android.application'
}

def testKeystorePath =
    System.getenv(
        "CITY_RESTAURANT_TEST_KEYSTORE"
    )

android {
    namespace 'com.cityrestaurant.game'
    compileSdk 36

    signingConfigs {
        testDebug {
            if (testKeystorePath) {
                storeFile file(testKeystorePath)
                storePassword "android"
                keyAlias "cityrestauranttest"
                keyPassword "android"
            }
        }
    }

    defaultConfig {
        applicationId "com.cityrestaurant.v2playtest"

        minSdk 23
        targetSdk 36

        versionCode 904
        versionName '0.9.4'
    }

    buildTypes {
        debug {
            minifyEnabled false

            if (testKeystorePath) {
                signingConfig signingConfigs.testDebug
            }
        }

        release {
            minifyEnabled false
        }
    }

    compileOptions {
        sourceCompatibility JavaVersion.VERSION_17
        targetCompatibility JavaVersion.VERSION_17
    }
}

dependencies {
}

